---

- name: Install MySQL server packages
  apt: name={{ item }} state=present
  with_items: 
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Create MySQL server configuration
  template: >
    src=my.cnf.j2
    dest={{ mysql_config_path }}
    owner=root
    group=root
    mode=0644
  notify: restart MySQL
  tags: mysql

- name: Ensure MySQL is running and enabled on boot
  service: name={{ mysql_service_name }} state=started enabled=yes
  tags: mysql

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
   - "{{ ansible_hostname|lower() }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: mysql_root_password != ''


- name: Create root user MySQL client configuration
  template: 
    src: root_dot_my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  when: mysql_root_password != ''
  tags: mysql

- name: Remove MySQL anonymous user
  mysql_user: name="" host={{ item }} state=absent
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

- name: Remove MySQL test database
  mysql_db: name=test state=absent
  tags: mysql

- name: create the databases
  mysql_db: 
    name: "{{ item.name }}"
    state: present
  with_items: mysql_db
  when: mysql_db|lower() != 'none'

- name: create the database users
  mysql_user: 
    name: "{{ item.name }}"
    password: "{{ item.pass|default('foobar') }}"
    priv: "{{ item.priv|default('*.*:ALL') }}"
    state: present 
    host: "{{ item.host | default('localhost') }}"
  with_items: mysql_users
  when: mysql_users|lower() != 'none'